[package]
name = "tea-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Core data structures and traits for tevec."

[features]
default = []
# default = ["ndarray", "time", "pl"]

ndarray = ["dep:ndarray"]
polars = ["dep:polars", "tea-error/polars"]
time = ["tea-dtype/time"]
serde = ["tea-dtype/serde"]

[dependencies]
num-traits = { workspace = true }
tea-error = { workspace = true }
tea-dtype = { workspace = true, default-features = false }
serde = "1.0"
ndarray = { version = "0.16", optional = true, features = ["rayon"] }
polars = { version = "0.41", optional = true, default-features = false, features = [
    "dtype-struct",
    "dtype-datetime",
    "dtype-duration",
] }

[dev-dependencies]
criterion = "0.5"


[[bench]]
name = "agg"
harness = false
