[package]
name = "tea-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
# default = ["ndarray", "time", "pl"]

pl = ["polars", "polars-arrow", "tea-error/polars"]
time = ["tea-dtype/time"]

[dependencies]
num-traits = { workspace = true }
tea-error = { path = "../tea-error", default-features = false }
tea-dtype = { path = "../tea-dtype", default-features = false }
serde = "1.0"
ndarray = { version = "0.15.6", optional = true, features = ["rayon"] }
polars = { version = "0.41.2", optional = true, default-features = false, features = [
    "dtype-struct",
    "dtype-datetime",
    "dtype-duration",
] }
polars-arrow = { version = "0.41.2", optional = true }
