[package]
name = "tea-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = []
# default = ["ndarray", "time", "pl"]

pl = ["polars", "polars-arrow", "tea-error/polars"]
time = ["tea-dtype/time"]

[dependencies]
num-traits = {workspace = true}
tea-error = {path = "../tea-error", default_features = false}
tea-dtype = {path = "../tea-dtype", default_features = false}
serde = "1.0"
ndarray = {version = "0.15.6", optional = true}
polars = {version = "0.39.0", optional = true, default_features = false}
polars-arrow = {version = "0.39.0", optional = true}
