[package]
name = "tea-time"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Time related dtypes for tevec"

[dependencies]
chrono = "0.4.37"
tea-error = { workspace = true }
