[package]
name = "tea-rolling"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tea-core = { path = "../tea-core", default-features = false }
num-traits = { workspace = true }