[package]
name = "tea-rolling"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tea-core = { path = "../tea-core", default-features = false }
num-traits = { workspace = true }