[package]
name = "tea-error"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = {workspace = true}
thiserror = {workspace = true}