[package]
name = "tea-agg"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Aggregate function for tevec"

[dependencies]
tea-core = { workspace = true, default-features = false }
