[package]
name = "tea-agg"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "Aggregate function for tevec"

[dependencies]
tea-core = { path = "../tea-core", default-features = false }
